version: 2
sca:
  ignored-vulnerabilities:
    - identifier: GHSA-w228-rfpx-fhm4
      path: qa/pdm.lock
      comment: 'Vulnerability does not concern this repository.'
      until: '2025-01-01T00:00:01Z'

